--- 
hapi: 
  fhir: 
    cors: 
      allow_Credentials: true
      allowed_origin: 
        - "*"
    fhir_version: R4
    search-coord-core-pool-size: 20
    search-coord-max-pool-size: 100
    search-coord-queue-capacity: 200
    tester: 
      global: 
        fhir_version: R4
        name: "Global Tester"
        refuse_to_fetch_third_party_urls: false
        server_address: "http://hapi.fhir.org/baseR4"
      home: 
        fhir_version: R4
        name: "Local Tester"
        refuse_to_fetch_third_party_urls: false
        server_address: "http://localhost:8090/fhir"
spring: 
  batch: 
    job: 
      enabled: false
  datasource: 
    driverClassName: org.h2.Driver
    hikari: 
      maximum-pool-size: 10
    max-active: 15
    password: ~
    url: "jdbc:h2:file:./target/database/h2"
    username: sa
  jpa: 
    properties: 
      hibernate.format_sql: false
      hibernate.show_sql: false
